[pytest]
filterwarnings =
    ignore:divide by zero encountered in matmul:RuntimeWarning
    ignore:overflow encountered in matmul:RuntimeWarning
    ignore:invalid value encountered in matmul:RuntimeWarning
